# Generated by Django 4.2.3 on 2023-07-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0002_rename_task_tasklist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasklist',
            options={'ordering': ['is_completed']},
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
